name: Overseerr CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-18.04
    container: node:12.18-alpine
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies
        env:
          HUSKY_SKIP_INSTALL: 1
        run: yarn
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
  build_and_push:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sctx/overseerr
          tags: latest
